hypervizors:
  hosts:
		yeager01:
			ansible_host: 192.168.1.2
			ansible_user: root
      usb_bind:
        - { kernel: "3-2", bind_to: mikasa01 } 
        - { kernel: "3-1", bind_to: mikasa01 } 
        - { kernel: "1-1.4", bind_to: mikasa02 } 
        - { kernel: "1-1.2", bind_to: mikasa02 } 
		yeager02:
			ansible_host: 192.168.1.3
			ansible_user: root
      usb_bind:
        - { kernel: "3-2", bind_to: mikasa03 } 
        - { kernel: "3-10", bind_to: mikasa03 } 
        - { kernel: "3-5", bind_to: mikasa04 } 
        - { kernel: "3-6", bind_to: mikasa04 } 
  children:
    cam_servers:
      hosts:
        yeager01:
virtuals:
  hosts:
    mikasa01:
      ansible_host: 192.168.1.80
      ansible_user: root
    mikasa02:
      ansible_host: 192.168.1.81
      ansible_user: root
